version: '3.4'
name: bitrix-app

services:
  web:
    build:
      context: deployment/php
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
  db:
    image: mariadb
    ports:
      - "5432:5432"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=test_pass
    volumes:
      - ./deployment/mariadb:/var/lib/mysql
